require: standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - "scratch/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
