require: standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
