#!/usr/bin/env ruby

# Add lib directory to load path
# lib_path = File.expand_path("../lib", __dir__)
# $LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

require "y_fantasy/cli"

YFantasy::CLI.start
